import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import express from 'express';
import pg from 'pg';
import dotenv from 'dotenv';
import { installSecurity, hashPassword } from '../security.js';
import { installOperations, balance } from '../operations.js';

dotenv.config({path:new URL('../.env',import.meta.url),quiet:true});
test('production contracts: auth, real stock, concurrency, retries, receipts and close-day', {skip:!process.env.RUN_ISOLATED_DB_TESTS},async()=>{
 const schema='production_test_'+crypto.randomBytes(8).toString('hex');
 const url=new URL(process.env.TEST_DATABASE_URL||process.env.DATABASE_URL);
 if(url.hostname.endsWith('.neon.tech'))url.hostname=url.hostname.replace('-pooler.','.');
 const admin=new pg.Pool({connectionString:url.toString(),connectionTimeoutMillis:10000});
 let db,server;
 const originalHash=process.env.ADMIN_PASSWORD_HASH;
 try {
  await admin.query(`CREATE SCHEMA ${schema}`);
  db=new pg.Pool({connectionString:url.toString(),options:`-c search_path=${schema}`,max:8,connectionTimeoutMillis:10000});
  await db.query(fs.readFileSync(new URL('../../schema.sql',import.meta.url),'utf8'));
  await db.query('ALTER TABLE salesmen ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255), ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE');
  await db.query(fs.readFileSync(new URL('../migrations/001_inventory_import.sql',import.meta.url),'utf8'));
  await db.query(fs.readFileSync(new URL('../migrations/002_production_integrity.sql',import.meta.url),'utf8'));
  const password=crypto.randomBytes(20).toString('hex');process.env.ADMIN_PASSWORD_HASH=hashPassword(password);
  const app=express();app.use(express.json());installSecurity(app,db);installOperations(app,db);
  server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  const base=`http://127.0.0.1:${server.address().port}/api/v2`;
  const call=async(path,body,token,key=crypto.randomUUID(),method=body===undefined?'GET':'POST')=>{
   console.log('Checking',method,path);
   const r=await fetch(base+path,{signal:AbortSignal.timeout(20000),method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),'Idempotency-Key':key},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()};
  };
  const ok=async(...args)=>{const r=await call(...args);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;};
  assert.equal((await call('/admin/login',{username:'admin',password:'wrong'})).status,401);
  assert.equal((await call('/admin/products')).status,401);
  const a=(await ok('/admin/login',{username:'admin',password})).token;
  const g=await ok('/admin/godowns',{name:'Test godown',active:true},a);
  const g2=await ok('/admin/godowns',{name:'Other godown',active:true},a);
  const p=await ok('/admin/products',{name:'Test product',price_paise:100,units_per_strip:5,strips_per_box:2,pieces_per_box:10,active:true},a);
  const v=await ok('/admin/vehicles',{name:'Test vehicle',godown_id:g.id},a);
  const person=await ok('/admin/salesmen',{name:'Test salesman',mobile:'9888888888',password,vehicle_id:v.id,status:'ACTIVE'},a);
  assert.equal(person.password_hash,undefined);assert.equal(person.has_password,true);
  const s=(await ok('/salesman/login',{mobile:'9888888888',password})).token;
  assert.equal((await call('/admin/products',undefined,s)).status,403);
  assert.equal((await call('/ADMIN/products',undefined,s)).status,403);
  assert.equal((await call('/unload-requests',undefined,s)).status,403);
  assert.equal((await call('/admin/products',{name:'bad','name) VALUES (1); --':'unsafe'},a)).status,400);
  const receipt={invoice_ref:'TEST-RECEIPT',godown_id:g.id,lines:[{product_id:p.id,quantity_pieces:100}]};const key=crypto.randomUUID();
  const purchase=await ok('/admin/purchases',receipt,a,key);assert.equal((await ok('/admin/purchases',receipt,a,key)).id,purchase.id);
  assert.equal(await balance(db,g.id,p.id),100);assert.equal(await balance(db,g2.id,p.id),0);
  assert.equal((await call('/admin/purchases',{...receipt,invoice_ref:'INVALID',lines:[{product_id:p.id,quantity_pieces:-1}]},a)).status,400);
  assert.equal((await call('/admin/purchases',receipt,a)).status,409);
  const day=(await ok('/salesman/work-days',{},s)).workDayId;
  await ok(`/salesman/work-days/${day}/state`,{state:'LOADING'},s);
  await ok('/salesman/loads',{workDayId:day,items:[{productId:p.id,quantityPieces:100}]},s);
  assert.equal(await balance(db,g.id,p.id),0);assert.equal(await balance(db,v.id,p.id),100);
  await ok(`/salesman/work-days/${day}/state`,{state:'ON_ROUTE'},s);
  const sale={workDayId:day,customerId:'walk-in',items:[{productId:p.id,quantityPieces:10}],totalAmountPaise:1000,paymentMode:'CASH'};
  const saleKey=crypto.randomUUID();const inv=await ok('/salesman/sales',sale,s,saleKey);
  assert.equal(await balance(db,v.id,p.id),90);
  assert.equal((await ok('/salesman/sales',sale,s,saleKey)).id,inv.id);
  assert.equal(await balance(db,v.id,p.id),90);
  assert.equal((await call('/salesman/sales',{...sale,items:[{productId:p.id,quantityPieces:100}],totalAmountPaise:10000},s)).status,409);
  assert.equal((await call('/salesman/sales',{...sale,totalAmountPaise:1},s)).status,409);
  const race=await Promise.all([call('/salesman/sales',{...sale,items:[{productId:p.id,quantityPieces:80}],totalAmountPaise:8000},s),call('/salesman/sales',{...sale,items:[{productId:p.id,quantityPieces:50}],totalAmountPaise:5000},s)]);
  assert.equal(race.filter(r=>r.status===200).length,1);assert.equal(race.filter(r=>r.status===409).length,1);
  assert.equal(number((await db.query('SELECT COUNT(*) FROM invoices')).rows[0].count),2);
  const winning=race.find(r=>r.status===200).data.id;await ok(`/salesman/invoices/${winning}/cancel`,{},s);await ok(`/salesman/invoices/${winning}/cancel`,{},s);
  assert.equal(await balance(db,v.id,p.id),90);
  const snapshot=await ok('/salesman/snapshot',undefined,s);assert.equal(snapshot.products.length,1);assert.equal(snapshot.workDays[0].cashSalesPaise,1000);assert.equal(snapshot.invoices[0].items[0].productSnapshot.name,'Test product');
  const unload={workDayId:day,cashCollected:1000,cashBreakdown:{NOTE_10:1},heldItems:{[p.id]:10},unloadedItems:{[p.id]:80}};
  assert.equal((await call('/unload-requests',{...unload,cashCollected:0},s)).status,400);
  await ok('/unload-requests',unload,s);
  const requests=await ok('/unload-requests',undefined,a);assert.equal(requests[0].status,'PENDING');assert.equal(requests[0].request_data.paymentTotals.cash,1000);
  assert.equal((await call(`/unload-requests/${day}/approve`,{},s)).status,403);
  await ok(`/unload-requests/${day}/send-back`,{note:'Check count'},a);
  await ok('/unload-requests',unload,s);
  await ok(`/unload-requests/${day}/approve`,{},a);await ok(`/unload-requests/${day}/approve`,{},a);
  assert.equal(await balance(db,g.id,p.id),80);assert.equal(await balance(db,v.id,p.id),10);
  assert.equal((await call('/salesman/sales',sale,s)).status,409);
  const next=(await ok('/salesman/work-days',{},s)).workDayId;assert.notEqual(next,day);
  const after=await ok('/salesman/snapshot',undefined,s);assert.equal(after.workDays.find(d=>d.workDayId===next).openingStockSnapshot[p.id],10);
  const stocks=await ok(`/admin/vehicles/${v.id}/stock`,undefined,a);assert.equal(stocks[0].quantity_pieces,10);
  await ok('/logout',{},s);assert.equal((await call('/salesman/snapshot',undefined,s)).status,401);
 } finally {
  process.env.ADMIN_PASSWORD_HASH=originalHash||'';
  if(server)await new Promise(r=>server.close(r));await db?.end();await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin.end();
 }
});
const number=Number;
